### ISSUE TITLE
New release of cwl-utils

### ISSUE THREAD

**Issue by illusional** [common-workflow-language/cwl-utils#17]
Hi @mr-c, would it be possible to release 0.4 of cwl-utlis? I've setup the [deprecation notice]() for cwlgen. Now that I've tested more of my changes and am more confident, I'd be keen to get the new python classes released.

#### Automated deployment

As we discussed, it might be possible to setup automated deployments on tag for this repo so you don't have to manually release yourself. We'd done something similar for python-cwlgen so that it's not a manual process and so you don't need credentials.

Steps are [here (Pypi deployment)](https://docs.travis-ci.com/user/deployment/pypi/). It looks like they've slightly changed since last time I did it, but essentially you add the following to the `.travis` file:

```yaml
deploy:
  provider: pypi
  username: "__token__"
  # credentials will be here in the next step
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: common-workflow-language/cwl-utils
```

Run this command with an API token for pypi
```bash
travis encrypt <your-api-token> --add deploy.password
```

Happy to help set this up, would just need to coordinate a time to get an API key.
