### ISSUE TITLE
types for input/output not consistent

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwl-utils#2]
```
cwlVersion: v1.0
class: Workflow

inputs:
 a: int
 b: int[]
 c:
   type: int?

outputs: {}

steps: {}
```
python:
```
IN: from cwl_utils.parser_v1_0 import load_document
IN: [i.type for i in load_document('test.cwl').inputs]
Out: 
['int',
 <cwl_utils.parser_v1_0.InputArraySchema at 0x7f9242121400>,
 ['null', 'int']]
```
Shouldn't the `InputArraySchema` object also be an array, for example array?
